name: magicsour
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  freezed: ^2.1.1
  build_runner: ^2.3.0
  freezed_annotation: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  google_sign_in: ^5.0.4
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

